# Set all versions
CUSTOM_BUILD_TYPE ?= Beta
CUSTOM_BUILD_DATE := $(shell date +%Y%m%d)
CUSTOM_PLATFORM_VERSION := 9.0

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(CUSTOM_BUILD))

ifeq ($(IS_GO_VERSION), true)
CUSTOM_VERSION := RevolutionOS_go_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
ROM_FINGERPRINT := RevolutionOS_go/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
else
CUSTOM_VERSION := RevolutionOS_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
ROM_FINGERPRINT := RevolutionOS/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
endif

CUSTOM_PROPERTIES := \
    ros.revolution.version=$(CUSTOM_VERSION) \
    ros.revolution.build_date=$(CUSTOM_BUILD_DATE) \
    ros.revolution.build_type=$(CUSTOM_BUILD_TYPE) \
    ros.revolution.fingerprint=$(ROM_FINGERPRINT)
